# Generated by Django 5.2 on 2025-05-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
