# Generated by Django 5.2.3 on 2025-06-20 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ambiente_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(default='Desconhecido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='unidade_med',
            field=models.CharField(default='Desconhecido', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='responsavel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='sig',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historico',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(),
        ),
    ]
