# Generated by Django 5.2.3 on 2025-06-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sensor_tipo_sensor_sensor_sensor_unidade_med_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor',
            new_name='tipo',
        ),
    ]
