# Generated by Django 5.2.3 on 2025-06-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historico_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='unidade_med',
        ),
    ]
